name: ci
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          black --check src scripts tests app
          isort --check-only src scripts tests app
          flake8 src scripts tests app
      - name: Tests
        run: pytest -q --maxfail=1 --disable-warnings
